[package]
edition = "2021"
name = "snake_game"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.63"

[lib]
crate-type = ["cdylib"]
